// ═══════════════════════════════════════════════════════════════════
// Google Fonts — Curated list of 200+ popular fonts
// Organized by category for easy browsing
// ═══════════════════════════════════════════════════════════════════

export interface GoogleFont {
  name: string;
  category: 'sans-serif' | 'serif' | 'display' | 'handwriting' | 'monospace';
}

export const GOOGLE_FONTS: GoogleFont[] = [
  // ─── Sans Serif ─────────────────────────────────────────────────
  { name: 'Inter', category: 'sans-serif' },
  { name: 'Roboto', category: 'sans-serif' },
  { name: 'Open Sans', category: 'sans-serif' },
  { name: 'Poppins', category: 'sans-serif' },
  { name: 'Nunito', category: 'sans-serif' },
  { name: 'Nunito Sans', category: 'sans-serif' },
  { name: 'Montserrat', category: 'sans-serif' },
  { name: 'Lato', category: 'sans-serif' },
  { name: 'Raleway', category: 'sans-serif' },
  { name: 'Outfit', category: 'sans-serif' },
  { name: 'Source Sans 3', category: 'sans-serif' },
  { name: 'Work Sans', category: 'sans-serif' },
  { name: 'DM Sans', category: 'sans-serif' },
  { name: 'Plus Jakarta Sans', category: 'sans-serif' },
  { name: 'Space Grotesk', category: 'sans-serif' },
  { name: 'Manrope', category: 'sans-serif' },
  { name: 'Figtree', category: 'sans-serif' },
  { name: 'Sora', category: 'sans-serif' },
  { name: 'Albert Sans', category: 'sans-serif' },
  { name: 'Lexend', category: 'sans-serif' },
  { name: 'Lexend Deca', category: 'sans-serif' },
  { name: 'Urbanist', category: 'sans-serif' },
  { name: 'Quicksand', category: 'sans-serif' },
  { name: 'Cabin', category: 'sans-serif' },
  { name: 'Karla', category: 'sans-serif' },
  { name: 'Mulish', category: 'sans-serif' },
  { name: 'Rubik', category: 'sans-serif' },
  { name: 'Barlow', category: 'sans-serif' },
  { name: 'Barlow Semi Condensed', category: 'sans-serif' },
  { name: 'Barlow Condensed', category: 'sans-serif' },
  { name: 'Josefin Sans', category: 'sans-serif' },
  { name: 'Ubuntu', category: 'sans-serif' },
  { name: 'PT Sans', category: 'sans-serif' },
  { name: 'PT Sans Narrow', category: 'sans-serif' },
  { name: 'Exo 2', category: 'sans-serif' },
  { name: 'Hind', category: 'sans-serif' },
  { name: 'Libre Franklin', category: 'sans-serif' },
  { name: 'Noto Sans', category: 'sans-serif' },
  { name: 'Noto Sans Display', category: 'sans-serif' },
  { name: 'IBM Plex Sans', category: 'sans-serif' },
  { name: 'Overpass', category: 'sans-serif' },
  { name: 'Titillium Web', category: 'sans-serif' },
  { name: 'Archivo', category: 'sans-serif' },
  { name: 'Archivo Narrow', category: 'sans-serif' },
  { name: 'Maven Pro', category: 'sans-serif' },
  { name: 'Signika', category: 'sans-serif' },
  { name: 'Signika Negative', category: 'sans-serif' },
  { name: 'Catamaran', category: 'sans-serif' },
  { name: 'Questrial', category: 'sans-serif' },
  { name: 'Red Hat Display', category: 'sans-serif' },
  { name: 'Red Hat Text', category: 'sans-serif' },
  { name: 'Public Sans', category: 'sans-serif' },
  { name: 'Commissioner', category: 'sans-serif' },
  { name: 'Geologica', category: 'sans-serif' },
  { name: 'Onest', category: 'sans-serif' },
  { name: 'Geist', category: 'sans-serif' },
  { name: 'Instrument Sans', category: 'sans-serif' },
  { name: 'General Sans', category: 'sans-serif' },
  { name: 'Satoshi', category: 'sans-serif' },
  { name: 'Be Vietnam Pro', category: 'sans-serif' },
  { name: 'Jost', category: 'sans-serif' },
  { name: 'Kanit', category: 'sans-serif' },
  { name: 'Prompt', category: 'sans-serif' },
  { name: 'Sarabun', category: 'sans-serif' },
  { name: 'Oxygen', category: 'sans-serif' },
  { name: 'Asap', category: 'sans-serif' },
  { name: 'Acme', category: 'sans-serif' },
  { name: 'ABeeZee', category: 'sans-serif' },
  { name: 'Assistant', category: 'sans-serif' },
  { name: 'Readex Pro', category: 'sans-serif' },
  { name: 'Encode Sans', category: 'sans-serif' },
  { name: 'Wix Madefor Display', category: 'sans-serif' },
  { name: 'Gabarito', category: 'sans-serif' },
  { name: 'Bricolage Grotesque', category: 'sans-serif' },

  // ─── Serif ──────────────────────────────────────────────────────
  { name: 'Playfair Display', category: 'serif' },
  { name: 'Merriweather', category: 'serif' },
  { name: 'Lora', category: 'serif' },
  { name: 'PT Serif', category: 'serif' },
  { name: 'Noto Serif', category: 'serif' },
  { name: 'Noto Serif Display', category: 'serif' },
  { name: 'Libre Baskerville', category: 'serif' },
  { name: 'Source Serif 4', category: 'serif' },
  { name: 'Crimson Text', category: 'serif' },
  { name: 'Crimson Pro', category: 'serif' },
  { name: 'Cormorant', category: 'serif' },
  { name: 'Cormorant Garamond', category: 'serif' },
  { name: 'DM Serif Display', category: 'serif' },
  { name: 'DM Serif Text', category: 'serif' },
  { name: 'EB Garamond', category: 'serif' },
  { name: 'Bitter', category: 'serif' },
  { name: 'Domine', category: 'serif' },
  { name: 'Spectral', category: 'serif' },
  { name: 'Vollkorn', category: 'serif' },
  { name: 'IBM Plex Serif', category: 'serif' },
  { name: 'Zilla Slab', category: 'serif' },
  { name: 'Cardo', category: 'serif' },
  { name: 'Arvo', category: 'serif' },
  { name: 'Frank Ruhl Libre', category: 'serif' },
  { name: 'Fraunces', category: 'serif' },
  { name: 'Newsreader', category: 'serif' },
  { name: 'Instrument Serif', category: 'serif' },
  { name: 'Young Serif', category: 'serif' },
  { name: 'Literata', category: 'serif' },
  { name: 'Gelasio', category: 'serif' },
  { name: 'Mate', category: 'serif' },
  { name: 'Alegreya', category: 'serif' },
  { name: 'Brygada 1918', category: 'serif' },
  { name: 'Taviraj', category: 'serif' },
  { name: 'Sorts Mill Goudy', category: 'serif' },
  { name: 'Old Standard TT', category: 'serif' },
  { name: 'Aleo', category: 'serif' },
  { name: 'Bree Serif', category: 'serif' },
  { name: 'Rokkitt', category: 'serif' },
  { name: 'Oranienbaum', category: 'serif' },
  { name: 'Marcellus', category: 'serif' },

  // ─── Display ────────────────────────────────────────────────────
  { name: 'Abril Fatface', category: 'display' },
  { name: 'Alfa Slab One', category: 'display' },
  { name: 'Righteous', category: 'display' },
  { name: 'Lobster', category: 'display' },
  { name: 'Lobster Two', category: 'display' },
  { name: 'Bebas Neue', category: 'display' },
  { name: 'Fredoka', category: 'display' },
  { name: 'Bungee', category: 'display' },
  { name: 'Bungee Shade', category: 'display' },
  { name: 'Permanent Marker', category: 'display' },
  { name: 'Passion One', category: 'display' },
  { name: 'Monoton', category: 'display' },
  { name: 'Comfortaa', category: 'display' },
  { name: 'Concert One', category: 'display' },
  { name: 'Bangers', category: 'display' },
  { name: 'Orbitron', category: 'display' },
  { name: 'Audiowide', category: 'display' },
  { name: 'Silkscreen', category: 'display' },
  { name: 'Press Start 2P', category: 'display' },
  { name: 'Chango', category: 'display' },
  { name: 'Archivo Black', category: 'display' },
  { name: 'Lilita One', category: 'display' },
  { name: 'Russo One', category: 'display' },
  { name: 'Bungee Inline', category: 'display' },
  { name: 'Climate Crisis', category: 'display' },
  { name: 'Dela Gothic One', category: 'display' },
  { name: 'Rampart One', category: 'display' },
  { name: 'Shrikhand', category: 'display' },
  { name: 'Unbounded', category: 'display' },

  // ─── Handwriting ────────────────────────────────────────────────
  { name: 'Dancing Script', category: 'handwriting' },
  { name: 'Caveat', category: 'handwriting' },
  { name: 'Pacifico', category: 'handwriting' },
  { name: 'Satisfy', category: 'handwriting' },
  { name: 'Great Vibes', category: 'handwriting' },
  { name: 'Sacramento', category: 'handwriting' },
  { name: 'Kalam', category: 'handwriting' },
  { name: 'Indie Flower', category: 'handwriting' },
  { name: 'Patrick Hand', category: 'handwriting' },
  { name: 'Shadows Into Light', category: 'handwriting' },
  { name: 'Courgette', category: 'handwriting' },
  { name: 'Cookie', category: 'handwriting' },
  { name: 'Handlee', category: 'handwriting' },
  { name: 'Gloria Hallelujah', category: 'handwriting' },
  { name: 'Architects Daughter', category: 'handwriting' },
  { name: 'Amatic SC', category: 'handwriting' },
  { name: 'Yellowtail', category: 'handwriting' },
  { name: 'Tangerine', category: 'handwriting' },
  { name: 'Playwrite DE Grund', category: 'handwriting' },
  { name: 'Alex Brush', category: 'handwriting' },

  // ─── Monospace ──────────────────────────────────────────────────
  { name: 'JetBrains Mono', category: 'monospace' },
  { name: 'Fira Code', category: 'monospace' },
  { name: 'Source Code Pro', category: 'monospace' },
  { name: 'Roboto Mono', category: 'monospace' },
  { name: 'IBM Plex Mono', category: 'monospace' },
  { name: 'Space Mono', category: 'monospace' },
  { name: 'Ubuntu Mono', category: 'monospace' },
  { name: 'Inconsolata', category: 'monospace' },
  { name: 'PT Mono', category: 'monospace' },
  { name: 'DM Mono', category: 'monospace' },
  { name: 'Cousine', category: 'monospace' },
  { name: 'Anonymous Pro', category: 'monospace' },
  { name: 'Red Hat Mono', category: 'monospace' },
  { name: 'Noto Sans Mono', category: 'monospace' },
  { name: 'Geist Mono', category: 'monospace' },
];

// All font names (for quick lookups)
export const FONT_NAMES = GOOGLE_FONTS.map(f => f.name);

// Category labels
export const FONT_CATEGORIES: { key: GoogleFont['category']; label: string }[] = [
  { key: 'sans-serif', label: 'Sans Serif' },
  { key: 'serif', label: 'Serif' },
  { key: 'display', label: 'Display' },
  { key: 'handwriting', label: 'Handwriting' },
  { key: 'monospace', label: 'Monospace' },
];

// Preload a font by injecting a Google Fonts link
const loadedFonts = new Set<string>();
export function preloadFont(fontName: string): void {
  if (loadedFonts.has(fontName)) return;
  loadedFonts.add(fontName);
  const link = document.createElement('link');
  link.rel = 'stylesheet';
  link.href = `https://fonts.googleapis.com/css2?family=${fontName.replace(/ /g, '+')}:wght@400;600;700&display=swap`;
  document.head.appendChild(link);
}
